image: ubuntu:bionic

pipelines:
  default:
    - step:
        script:
          # Dependencies
          - apt update
          - apt -y install cmake build-essential curl mercurial lsb-release wget g++-8 libtinyxml-dev libxml2-utils ruby-dev python-psutil cppcheck
          - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8
          - gcc -v
          - g++ -v
          - gcov -v
          # lcov
          - git clone https://github.com/linux-test-project/lcov.git
          - cd lcov
          - make install
          - cd ..
          # Static checking before building - fail fast
          - sh tools/code_check.sh
          # Ignition cmake
          - hg clone http://bitbucket.org/ignitionrobotics/ign-cmake -b gz11
          - cd ign-cmake
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition tools
          - hg clone http://bitbucket.org/ignitionrobotics/ign-tools
          - cd ign-tools
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition math
          - hg clone http://bitbucket.org/ignitionrobotics/ign-math -b gz11
          - cd ign-math
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # SDFormat
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=coverage
          - make -j4
          - make test
          - make coverage
          # Use a special version of codecov for handling gcc8 output.
          - bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/4678d212cce2078bbaaf5027af0c0dafaad6a095/codecov) -X gcovout 2>/dev/null
          - make install
          # Examples
          - cd ..
          - cd examples
          - mkdir build
          - cd build
          - cmake ..
          - make -j4
          - ./simple ../simple.sdf
